[tool.poetry]
name = "wordlist"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{include = "wordlist", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
setuptools = "^67.8.0"
loguru = "^0.7.0"
pyexcel = "^0.7.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


#
# 在单元测试打印 log 方法: poetry run pytest --capture=no
#
[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
