version: "3"

includes:
  std:
    taskfile: ~/.local/task/better-sre/config/Taskfile.yml
    dir: ~/.local/task/better-sre/config # global path
    optional: true #

  chain:
    taskfile: packages/chain/Taskfile.yml
    dir: packages/chain/
    optional: true #

  rss:
    taskfile: packages/rsshub/Taskfile.yml
    dir: packages/rsshub/
    optional: true #

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env


################################################################################################


tasks:

  setup:
    cmds:
      - pyenv install 3.9.9
      - pyenv virtualenv 3.9.9 py39-toolbox
      - pyenv local py39-toolbox

  install:
    cmds:
      - pip3 install -r requirements.txt

  init:
    cmds:
      - task init:env
      - task install

  init:env:
    cmds:
      - cp .env.local .env

  ##################################################################################################

  run:eth:
    cmds:
      - task: chain:run

  run:
    cmds:
      - task: rss:run