version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env


################################################################################################


tasks:
  install:
    cmds:
      - pip3 install -r requirements.txt

  init:
    cmds:
      - task init:env
      - task install

  init:env:
    cmds:
      - cp .env.local .env

  ##################################################################################################

  run:eth:
    cmds:
      - |
        cd packages/chain; python3 cmd/eth.py \
          --rpc_url=${INFURA_RPC_URL} \
          --etherscan_api_key=${ETHERSCAN_API_KEY} \
          --address=${ETH_ADDRESS} \
        

  run:
    cmds:
      - cd packages/rsshub; python3 run.py