version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing


################################################################################################


tasks:
  install:
    cmds:
      - pip3 install -r requirements.txt

  run:
    cmds:
      - |
        python3 run.py \
