version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing


################################################################################################


tasks:
  run:
    cmds:
      - |
        python3 run.py \
          --token=${DISCORD_TOKEN} \
          --http_proxy=${HTTP_PROXY}
